#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_TITLE "Chaos Chess"
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define PIECE_TEXTURE_WIDTH 10
#define PIECE_TEXTURE_HEIGHT 19

#define BOARD_PIXELS_LENGTH (PIECE_TEXTURE_WIDTH * 12)
#define BOARD_CELL_LENGTH 15
#define BOARD_VERTICAL_MARGIN 20
#define BOARD_HORIZONTAL_MARGIN 40

#define BOARD_UNSELECTED_X_SENTINEL -1

#define PROMOTION_BUTTON_WIDTH 24
#define PROMOTION_BUTTON_SPACING 4

#endif
