#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_TITLE "Chaos Chess"
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define PIECE_TEXTURE_WIDTH 10
#define PIECE_TEXTURE_HEIGHT 19

#define BOARD_PIXELS_LENGTH (PIECE_TEXTURE_WIDTH * 12)
#define BOARD_CELL_LENGTH 15
#define BOARD_VERTICAL_MARGIN 100

#endif
